import type { Opportunity } from "./types";

// Mock dataset — structured for easy DeFiLlama / CoinGecko swap
export const opportunities: Opportunity[] = [
  {
    id: "aave-v3-eth-usdc",
    protocol: "Aave V3",
    protocolLogo: "AV",
    chain: "Ethereum",
    strategyType: "Lending",
    baseAPY: 4.82,
    incentiveAPY: 0.41,
    totalAPY: 5.23,
    tvl: 1_840_000_000,
    riskScore: 2.1,
    riskLevel: "Low",
    riskBreakdown: { smartContract: 1.5, tokenVolatility: 2, impermanentLoss: 1, liquidityDepth: 2, protocolReputation: 1 },
    liquidityDepth: 920_000_000,
    volatility30d: 0.4,
    yieldSource: "Interest from USDC borrowers, supplemented by AAVE token emissions",
    bestUseCase: "Conservative treasury allocation — stable yield with deep exit liquidity",
    audited: true,
    auditFirms: ["Trail of Bits", "OpenZeppelin", "Certora"],
    contractAge: 38,
    historicalAPY: genHistory(5.23, 24),
    comparables: ["compound-v3-eth-usdc", "spark-dai"],
    tags: ["Stablecoin", "Blue Chip", "No IL"],
    url: "https://app.aave.com",
  },
  {
    id: "compound-v3-eth-usdc",
    protocol: "Compound V3",
    protocolLogo: "CO",
    chain: "Ethereum",
    strategyType: "Lending",
    baseAPY: 4.51,
    incentiveAPY: 0.78,
    totalAPY: 5.29,
    tvl: 920_000_000,
    riskScore: 2.4,
    riskLevel: "Low",
    riskBreakdown: { smartContract: 2, tokenVolatility: 2, impermanentLoss: 1, liquidityDepth: 2.5, protocolReputation: 1.5 },
    liquidityDepth: 460_000_000,
    volatility30d: 0.4,
    yieldSource: "USDC lending interest + COMP governance token incentives",
    bestUseCase: "Yield on idle USDC reserves with COMP optionality upside",
    audited: true,
    auditFirms: ["OpenZeppelin", "ChainSecurity"],
    contractAge: 32,
    historicalAPY: genHistory(5.29, 24),
    comparables: ["aave-v3-eth-usdc", "spark-dai"],
    tags: ["Stablecoin", "Blue Chip", "No IL"],
    url: "https://app.compound.finance",
  },
  {
    id: "spark-dai",
    protocol: "Spark Protocol",
    protocolLogo: "SP",
    chain: "Ethereum",
    strategyType: "Lending",
    baseAPY: 5.00,
    incentiveAPY: 0.0,
    totalAPY: 5.00,
    tvl: 2_200_000_000,
    riskScore: 1.9,
    riskLevel: "Low",
    riskBreakdown: { smartContract: 1.5, tokenVolatility: 1.5, impermanentLoss: 1, liquidityDepth: 1.5, protocolReputation: 1 },
    liquidityDepth: 1_100_000_000,
    volatility30d: 0.1,
    yieldSource: "MakerDAO DSR — DAI savings rate set by governance, backed by RWA collateral",
    bestUseCase: "Institutional-grade stable yield — closest DeFi equivalent to a money market fund",
    audited: true,
    auditFirms: ["Trail of Bits", "ChainSecurity", "Certora"],
    contractAge: 14,
    historicalAPY: genHistory(5.0, 24),
    comparables: ["aave-v3-eth-usdc", "compound-v3-eth-usdc"],
    tags: ["Stablecoin", "RWA-backed", "No IL", "DAI"],
    url: "https://app.spark.fi",
  },
  {
    id: "lido-steth",
    protocol: "Lido",
    protocolLogo: "LI",
    chain: "Ethereum",
    strategyType: "Liquid Staking",
    baseAPY: 3.91,
    incentiveAPY: 0.0,
    totalAPY: 3.91,
    tvl: 28_400_000_000,
    riskScore: 2.8,
    riskLevel: "Low",
    riskBreakdown: { smartContract: 2.5, tokenVolatility: 3, impermanentLoss: 1, liquidityDepth: 1.5, protocolReputation: 2 },
    liquidityDepth: 8_200_000_000,
    volatility30d: 18.2,
    yieldSource: "Ethereum validator consensus + execution layer rewards (MEV included)",
    bestUseCase: "Core ETH position with liquid yield — no lock-up, stETH accepted as collateral elsewhere",
    audited: true,
    auditFirms: ["Sigma Prime", "Quantstamp", "MixBytes"],
    contractAge: 40,
    historicalAPY: genHistory(3.91, 24),
    comparables: ["rocketpool-reth", "mantle-meth"],
    tags: ["ETH", "Liquid", "No IL", "MEV"],
    url: "https://lido.fi",
  },
  {
    id: "rocketpool-reth",
    protocol: "Rocket Pool",
    protocolLogo: "RP",
    chain: "Ethereum",
    strategyType: "Liquid Staking",
    baseAPY: 3.74,
    incentiveAPY: 0.0,
    totalAPY: 3.74,
    tvl: 3_100_000_000,
    riskScore: 3.2,
    riskLevel: "Low",
    riskBreakdown: { smartContract: 3, tokenVolatility: 3.5, impermanentLoss: 1, liquidityDepth: 3.5, protocolReputation: 2 },
    liquidityDepth: 620_000_000,
    volatility30d: 18.2,
    yieldSource: "ETH staking rewards + node operator fee distribution via rETH rebase",
    bestUseCase: "Decentralization-preferred ETH yield — higher censorship resistance than Lido",
    audited: true,
    auditFirms: ["Sigma Prime", "Consensys Diligence"],
    contractAge: 36,
    historicalAPY: genHistory(3.74, 24),
    comparables: ["lido-steth", "mantle-meth"],
    tags: ["ETH", "Liquid", "Decentralized", "No IL"],
    url: "https://rocketpool.net",
  },
  {
    id: "uniswap-v3-usdc-eth",
    protocol: "Uniswap V3",
    protocolLogo: "UN",
    chain: "Ethereum",
    strategyType: "LP",
    baseAPY: 12.4,
    incentiveAPY: 0.0,
    totalAPY: 12.4,
    tvl: 340_000_000,
    riskScore: 5.8,
    riskLevel: "Medium",
    riskBreakdown: { smartContract: 2, tokenVolatility: 7, impermanentLoss: 8, liquidityDepth: 3, protocolReputation: 1.5 },
    liquidityDepth: 170_000_000,
    volatility30d: 42.1,
    yieldSource: "0.3% swap fees from USDC/ETH trading volume, concentrated liquidity range",
    bestUseCase: "Active yield on ETH exposure — requires range management, suits quant desks",
    audited: true,
    auditFirms: ["Trail of Bits", "ABDK"],
    contractAge: 42,
    historicalAPY: genHistory(12.4, 24),
    comparables: ["curve-3pool", "balancer-eth-usdc"],
    tags: ["LP", "Active Management", "High Fee", "IL Risk"],
    url: "https://app.uniswap.org",
  },
  {
    id: "curve-3pool",
    protocol: "Curve Finance",
    protocolLogo: "CV",
    chain: "Ethereum",
    strategyType: "LP",
    baseAPY: 1.82,
    incentiveAPY: 2.14,
    totalAPY: 3.96,
    tvl: 840_000_000,
    riskScore: 3.1,
    riskLevel: "Low",
    riskBreakdown: { smartContract: 2.5, tokenVolatility: 2, impermanentLoss: 2, liquidityDepth: 2, protocolReputation: 2 },
    liquidityDepth: 420_000_000,
    volatility30d: 0.3,
    yieldSource: "Trading fees from stablecoin swaps + CRV + veCRV bribe revenue",
    bestUseCase: "Stablecoin yield with minimal IL — good for large allocations that need depth",
    audited: true,
    auditFirms: ["Trail of Bits", "MixBytes"],
    contractAge: 56,
    historicalAPY: genHistory(3.96, 24),
    comparables: ["aave-v3-eth-usdc", "spark-dai"],
    tags: ["Stablecoin", "Low IL", "veCRV"],
    url: "https://curve.fi",
  },
  {
    id: "pendle-pt-usde",
    protocol: "Pendle Finance",
    protocolLogo: "PE",
    chain: "Ethereum",
    strategyType: "Structured",
    baseAPY: 8.91,
    incentiveAPY: 1.2,
    totalAPY: 10.11,
    tvl: 480_000_000,
    riskScore: 4.8,
    riskLevel: "Medium",
    riskBreakdown: { smartContract: 4, tokenVolatility: 5, impermanentLoss: 3, liquidityDepth: 4, protocolReputation: 3 },
    liquidityDepth: 192_000_000,
    volatility30d: 1.8,
    yieldSource: "Fixed-rate yield via USDe principal tokens — locks in yield at purchase price",
    bestUseCase: "Fixed-income alternative — hedge against variable rate compression, suits ALM desks",
    audited: true,
    auditFirms: ["Ackee Blockchain", "Dedaub"],
    contractAge: 18,
    historicalAPY: genHistory(10.11, 24),
    comparables: ["aave-v3-eth-usdc", "spark-dai"],
    tags: ["Fixed Rate", "Structured", "USDe", "No IL"],
    url: "https://app.pendle.finance",
  },
  {
    id: "gmx-v2-arb",
    protocol: "GMX V2",
    protocolLogo: "GM",
    chain: "Arbitrum",
    strategyType: "Structured",
    baseAPY: 14.2,
    incentiveAPY: 3.8,
    totalAPY: 18.0,
    tvl: 620_000_000,
    riskScore: 6.4,
    riskLevel: "High",
    riskBreakdown: { smartContract: 5, tokenVolatility: 7, impermanentLoss: 6, liquidityDepth: 5, protocolReputation: 4 },
    liquidityDepth: 248_000_000,
    volatility30d: 35.4,
    yieldSource: "Perp trader fees (70%) + GMX token emissions — GLP acts as counterparty to leveraged traders",
    bestUseCase: "High-yield allocation with directional hedge — GLP profits when traders lose",
    audited: true,
    auditFirms: ["ABDK", "Quantstamp"],
    contractAge: 24,
    historicalAPY: genHistory(18.0, 24),
    comparables: ["uniswap-v3-usdc-eth"],
    tags: ["Perp Fees", "Arbitrum", "High Yield", "Counterparty"],
    url: "https://gmx.io",
  },
  {
    id: "aave-v3-arb-usdc",
    protocol: "Aave V3",
    protocolLogo: "AV",
    chain: "Arbitrum",
    strategyType: "Lending",
    baseAPY: 5.91,
    incentiveAPY: 1.2,
    totalAPY: 7.11,
    tvl: 680_000_000,
    riskScore: 2.6,
    riskLevel: "Low",
    riskBreakdown: { smartContract: 1.5, tokenVolatility: 2, impermanentLoss: 1, liquidityDepth: 2.5, protocolReputation: 1 },
    liquidityDepth: 340_000_000,
    volatility30d: 0.4,
    yieldSource: "USDC lending interest on Arbitrum + ARB token incentives from ecosystem grants",
    bestUseCase: "Higher-yield stable allocation — same credit quality as mainnet Aave, extra L2 incentives",
    audited: true,
    auditFirms: ["Trail of Bits", "OpenZeppelin"],
    contractAge: 26,
    historicalAPY: genHistory(7.11, 24),
    comparables: ["aave-v3-eth-usdc", "compound-v3-eth-usdc"],
    tags: ["Stablecoin", "L2", "No IL", "ARB Incentives"],
    url: "https://app.aave.com",
  },
  {
    id: "morpho-steakusdc",
    protocol: "Morpho Blue",
    protocolLogo: "MO",
    chain: "Ethereum",
    strategyType: "Lending",
    baseAPY: 6.34,
    incentiveAPY: 0.8,
    totalAPY: 7.14,
    tvl: 290_000_000,
    riskScore: 3.5,
    riskLevel: "Low",
    riskBreakdown: { smartContract: 3, tokenVolatility: 2, impermanentLoss: 1, liquidityDepth: 4, protocolReputation: 3 },
    liquidityDepth: 145_000_000,
    volatility30d: 0.4,
    yieldSource: "Optimized lending rates via autonomous market makers — routes to highest Aave/Compound supply rate",
    bestUseCase: "Yield optimization on USDC — 10-20% better rates vs. Aave/Compound with same collateral backing",
    audited: true,
    auditFirms: ["Spearbit", "Trail of Bits"],
    contractAge: 16,
    historicalAPY: genHistory(7.14, 24),
    comparables: ["aave-v3-eth-usdc", "compound-v3-eth-usdc"],
    tags: ["Stablecoin", "Optimized", "No IL", "Morpho"],
    url: "https://app.morpho.org",
  },
  {
    id: "mantle-meth",
    protocol: "Mantle LSP",
    protocolLogo: "ML",
    chain: "Ethereum",
    strategyType: "Liquid Staking",
    baseAPY: 4.14,
    incentiveAPY: 0.62,
    totalAPY: 4.76,
    tvl: 1_040_000_000,
    riskScore: 3.8,
    riskLevel: "Medium",
    riskBreakdown: { smartContract: 4, tokenVolatility: 3.5, impermanentLoss: 1, liquidityDepth: 4, protocolReputation: 3 },
    liquidityDepth: 260_000_000,
    volatility30d: 18.2,
    yieldSource: "ETH staking rewards + MNT token incentives — mETH accrues value vs ETH over time",
    bestUseCase: "Enhanced LST yield — higher APY than Lido/Rocket Pool with additional token upside",
    audited: true,
    auditFirms: ["Sigma Prime", "Halborn"],
    contractAge: 12,
    historicalAPY: genHistory(4.76, 24),
    comparables: ["lido-steth", "rocketpool-reth"],
    tags: ["ETH", "Liquid", "MNT Incentives"],
    url: "https://meth.mantle.xyz",
  },
  {
    id: "ondo-usdy",
    protocol: "Ondo Finance",
    protocolLogo: "ON",
    chain: "Ethereum",
    strategyType: "RWA",
    baseAPY: 5.10,
    incentiveAPY: 0.0,
    totalAPY: 5.10,
    tvl: 420_000_000,
    riskScore: 2.3,
    riskLevel: "Low",
    riskBreakdown: { smartContract: 2, tokenVolatility: 1, impermanentLoss: 1, liquidityDepth: 3, protocolReputation: 2 },
    liquidityDepth: 210_000_000,
    volatility30d: 0.1,
    yieldSource: "US Treasury yield tokenized on-chain — USDY backed 1:1 by short-duration Treasuries",
    bestUseCase: "Regulatory-compliant yield — near risk-free rate on-chain, KYC required",
    audited: true,
    auditFirms: ["Trail of Bits", "Quantstamp"],
    contractAge: 18,
    historicalAPY: genHistory(5.10, 24),
    comparables: ["spark-dai", "aave-v3-eth-usdc"],
    tags: ["RWA", "T-Bills", "KYC", "Compliant"],
    url: "https://ondo.finance",
  },
  {
    id: "balancer-eth-usdc",
    protocol: "Balancer V2",
    protocolLogo: "BA",
    chain: "Ethereum",
    strategyType: "LP",
    baseAPY: 4.2,
    incentiveAPY: 2.9,
    totalAPY: 7.1,
    tvl: 180_000_000,
    riskScore: 5.1,
    riskLevel: "Medium",
    riskBreakdown: { smartContract: 3, tokenVolatility: 6, impermanentLoss: 6, liquidityDepth: 4, protocolReputation: 3 },
    liquidityDepth: 90_000_000,
    volatility30d: 38.7,
    yieldSource: "0.1% swap fees + BAL incentives + veBAL bribe revenue from Aura/Hidden Hand",
    bestUseCase: "Diversified LP exposure — 80/20 WETH/USDC pool limits IL vs 50/50",
    audited: true,
    auditFirms: ["Trail of Bits", "Certora"],
    contractAge: 44,
    historicalAPY: genHistory(7.1, 24),
    comparables: ["uniswap-v3-usdc-eth", "curve-3pool"],
    tags: ["LP", "80/20", "veBAL", "Moderate IL"],
    url: "https://app.balancer.fi",
  },
  {
    id: "yearn-v3-usdc",
    protocol: "Yearn V3",
    protocolLogo: "YE",
    chain: "Ethereum",
    strategyType: "Structured",
    baseAPY: 6.8,
    incentiveAPY: 0.5,
    totalAPY: 7.3,
    tvl: 155_000_000,
    riskScore: 4.2,
    riskLevel: "Medium",
    riskBreakdown: { smartContract: 4, tokenVolatility: 2, impermanentLoss: 1, liquidityDepth: 4.5, protocolReputation: 3 },
    liquidityDepth: 77_500_000,
    volatility30d: 0.5,
    yieldSource: "Auto-compound across Aave, Compound, Morpho — allocates dynamically to highest rate",
    bestUseCase: "Set-and-forget USDC yield optimization — gas-efficient vault batches harvests across strategies",
    audited: true,
    auditFirms: ["Trail of Bits", "Spearbit"],
    contractAge: 52,
    historicalAPY: genHistory(7.3, 24),
    comparables: ["morpho-steakusdc", "aave-v3-eth-usdc"],
    tags: ["Auto-Compound", "Stablecoin", "Vault", "No IL"],
    url: "https://yearn.fi",
  },
];

function genHistory(baseAPY: number, months: number): { date: string; apy: number }[] {
  const result = [];
  const now = new Date();
  for (let i = months; i >= 0; i--) {
    const d = new Date(now);
    d.setMonth(d.getMonth() - i);
    const noise = (Math.random() - 0.5) * baseAPY * 0.4;
    result.push({
      date: d.toISOString().slice(0, 10),
      apy: Math.max(0.1, Math.round((baseAPY + noise) * 100) / 100),
    });
  }
  return result;
}

export function getOpportunity(id: string): Opportunity | undefined {
  return opportunities.find((o) => o.id === id);
}

export function getComparables(ids: string[]): Opportunity[] {
  return ids.map((id) => opportunities.find((o) => o.id === id)).filter(Boolean) as Opportunity[];
}
