// Static enrichment data keyed by DeFiLlama pool ID.
// Live yield/TVL/APY comes from the API; everything else is curated here.

import type { Chain, StrategyType } from "./types";

export interface PoolEnrichment {
  id: string; // our internal slug (used for URL routing)
  poolId: string; // DeFiLlama pool UUID
  protocol: string;
  protocolLogo: string;
  chain: Chain;
  strategyType: StrategyType;
  yieldSource: string;
  bestUseCase: string;
  audited: boolean;
  auditFirms: string[];
  riskBreakdown: {
    smartContract: number;
    tokenVolatility: number;
    impermanentLoss: number;
    liquidityDepth: number;
    protocolReputation: number;
  };
  tags: string[];
  url: string;
  comparables: string[]; // other poolIds
}

export const POOL_ENRICHMENTS: PoolEnrichment[] = [
  {
    id: "aave-v3-eth-usdc",
    poolId: "aa70268e-4b52-42bf-a116-608b370f9501",
    protocol: "Aave V3",
    protocolLogo: "AV",
    chain: "Ethereum",
    strategyType: "Lending",
    yieldSource: "Interest from USDC borrowers, supplemented by AAVE token emissions",
    bestUseCase: "Conservative treasury allocation — stable yield with deep exit liquidity",
    audited: true,
    auditFirms: ["Trail of Bits", "OpenZeppelin", "Certora"],
    riskBreakdown: { smartContract: 1.5, tokenVolatility: 2, impermanentLoss: 1, liquidityDepth: 2, protocolReputation: 1 },
    tags: ["Stablecoin", "Blue Chip", "No IL"],
    url: "https://app.aave.com",
    comparables: ["7da72d09-56ca-4ec5-a45f-59114353e487", "54e9b138-3146-4c1f-8dce-1cb948f5ef96"],
  },
  {
    id: "compound-v3-eth-usdc",
    poolId: "7da72d09-56ca-4ec5-a45f-59114353e487",
    protocol: "Compound V3",
    protocolLogo: "CO",
    chain: "Ethereum",
    strategyType: "Lending",
    yieldSource: "USDC lending interest + COMP governance token incentives",
    bestUseCase: "Yield on idle USDC reserves with COMP optionality upside",
    audited: true,
    auditFirms: ["OpenZeppelin", "ChainSecurity"],
    riskBreakdown: { smartContract: 2, tokenVolatility: 2, impermanentLoss: 1, liquidityDepth: 2.5, protocolReputation: 1.5 },
    tags: ["Stablecoin", "Blue Chip", "No IL"],
    url: "https://app.compound.finance",
    comparables: ["aa70268e-4b52-42bf-a116-608b370f9501", "54e9b138-3146-4c1f-8dce-1cb948f5ef96"],
  },
  {
    id: "spark-usds",
    poolId: "54e9b138-3146-4c1f-8dce-1cb948f5ef96",
    protocol: "Spark Protocol",
    protocolLogo: "SP",
    chain: "Ethereum",
    strategyType: "Lending",
    yieldSource: "MakerDAO/Sky DSR — USDS savings rate set by governance, backed by RWA collateral",
    bestUseCase: "Institutional-grade stable yield — closest DeFi equivalent to a money market fund",
    audited: true,
    auditFirms: ["Trail of Bits", "ChainSecurity", "Certora"],
    riskBreakdown: { smartContract: 1.5, tokenVolatility: 1.5, impermanentLoss: 1, liquidityDepth: 1.5, protocolReputation: 1 },
    tags: ["Stablecoin", "RWA-backed", "No IL", "USDS"],
    url: "https://app.spark.fi",
    comparables: ["aa70268e-4b52-42bf-a116-608b370f9501", "7da72d09-56ca-4ec5-a45f-59114353e487"],
  },
  {
    id: "lido-steth",
    poolId: "747c1d2a-c668-4682-b9f9-296708a3dd90",
    protocol: "Lido",
    protocolLogo: "LI",
    chain: "Ethereum",
    strategyType: "Liquid Staking",
    yieldSource: "Ethereum validator consensus + execution layer rewards (MEV included)",
    bestUseCase: "Core ETH position with liquid yield — no lock-up, stETH accepted as collateral elsewhere",
    audited: true,
    auditFirms: ["Sigma Prime", "Quantstamp", "MixBytes"],
    riskBreakdown: { smartContract: 2.5, tokenVolatility: 3, impermanentLoss: 1, liquidityDepth: 1.5, protocolReputation: 2 },
    tags: ["ETH", "Liquid", "No IL", "MEV"],
    url: "https://lido.fi",
    comparables: ["d4b3c522-6127-4b89-bedf-83641cdcd2eb", "b9f2f00a-ba96-4589-a171-dde979a23d87"],
  },
  {
    id: "rocketpool-reth",
    poolId: "d4b3c522-6127-4b89-bedf-83641cdcd2eb",
    protocol: "Rocket Pool",
    protocolLogo: "RP",
    chain: "Ethereum",
    strategyType: "Liquid Staking",
    yieldSource: "ETH staking rewards + node operator fee distribution via rETH rebase",
    bestUseCase: "Decentralization-preferred ETH yield — higher censorship resistance than Lido",
    audited: true,
    auditFirms: ["Sigma Prime", "Consensys Diligence"],
    riskBreakdown: { smartContract: 3, tokenVolatility: 3.5, impermanentLoss: 1, liquidityDepth: 3.5, protocolReputation: 2 },
    tags: ["ETH", "Liquid", "Decentralized", "No IL"],
    url: "https://rocketpool.net",
    comparables: ["747c1d2a-c668-4682-b9f9-296708a3dd90", "b9f2f00a-ba96-4589-a171-dde979a23d87"],
  },
  {
    id: "uniswap-v3-usdc-eth",
    poolId: "665dc8bc-c79d-4800-97f7-304bf368e547",
    protocol: "Uniswap V3",
    protocolLogo: "UN",
    chain: "Ethereum",
    strategyType: "LP",
    yieldSource: "0.3% swap fees from USDC/ETH trading volume, concentrated liquidity range",
    bestUseCase: "Active yield on ETH exposure — requires range management, suits quant desks",
    audited: true,
    auditFirms: ["Trail of Bits", "ABDK"],
    riskBreakdown: { smartContract: 2, tokenVolatility: 7, impermanentLoss: 8, liquidityDepth: 3, protocolReputation: 1.5 },
    tags: ["LP", "Active Management", "High Fee", "IL Risk"],
    url: "https://app.uniswap.org",
    comparables: ["25171c4c-1877-449a-9f88-45a9f153ee31", "201e5f6e-cf75-4d0e-b07f-d58da3cee23a"],
  },
  {
    id: "curve-3pool",
    poolId: "25171c4c-1877-449a-9f88-45a9f153ee31",
    protocol: "Curve Finance",
    protocolLogo: "CV",
    chain: "Ethereum",
    strategyType: "LP",
    yieldSource: "Trading fees from stablecoin swaps + CRV + veCRV bribe revenue",
    bestUseCase: "Stablecoin yield with minimal IL — good for large allocations that need depth",
    audited: true,
    auditFirms: ["Trail of Bits", "MixBytes"],
    riskBreakdown: { smartContract: 2.5, tokenVolatility: 2, impermanentLoss: 2, liquidityDepth: 2, protocolReputation: 2 },
    tags: ["Stablecoin", "Low IL", "veCRV"],
    url: "https://curve.fi",
    comparables: ["aa70268e-4b52-42bf-a116-608b370f9501", "54e9b138-3146-4c1f-8dce-1cb948f5ef96"],
  },
  {
    id: "pendle-usdg",
    poolId: "8bc218ed-faf1-41e9-a636-2989e9f7e805",
    protocol: "Pendle Finance",
    protocolLogo: "PE",
    chain: "Ethereum",
    strategyType: "Structured",
    yieldSource: "Fixed-rate yield via principal tokens — locks in yield at purchase price",
    bestUseCase: "Fixed-income alternative — hedge against variable rate compression, suits ALM desks",
    audited: true,
    auditFirms: ["Ackee Blockchain", "Dedaub"],
    riskBreakdown: { smartContract: 4, tokenVolatility: 5, impermanentLoss: 3, liquidityDepth: 4, protocolReputation: 3 },
    tags: ["Fixed Rate", "Structured", "No IL"],
    url: "https://app.pendle.finance",
    comparables: ["aa70268e-4b52-42bf-a116-608b370f9501", "54e9b138-3146-4c1f-8dce-1cb948f5ef96"],
  },
  {
    id: "gmx-v2-arb",
    poolId: "61b4c35c-97f6-4c05-a5ff-aeb4426adf5b",
    protocol: "GMX V2",
    protocolLogo: "GM",
    chain: "Arbitrum",
    strategyType: "Structured",
    yieldSource: "Perp trader fees (70%) + GMX token emissions — GM pool acts as counterparty to leveraged traders",
    bestUseCase: "High-yield allocation with directional hedge — GM profits when traders lose",
    audited: true,
    auditFirms: ["ABDK", "Quantstamp"],
    riskBreakdown: { smartContract: 5, tokenVolatility: 7, impermanentLoss: 6, liquidityDepth: 5, protocolReputation: 4 },
    tags: ["Perp Fees", "Arbitrum", "High Yield", "Counterparty"],
    url: "https://gmx.io",
    comparables: ["665dc8bc-c79d-4800-97f7-304bf368e547"],
  },
  {
    id: "aave-v3-arb-usdc",
    poolId: "d9fa8e14-0447-4207-9ae8-7810199dfa1f",
    protocol: "Aave V3",
    protocolLogo: "AV",
    chain: "Arbitrum",
    strategyType: "Lending",
    yieldSource: "USDC lending interest on Arbitrum + ARB token incentives from ecosystem grants",
    bestUseCase: "Higher-yield stable allocation — same credit quality as mainnet Aave, extra L2 incentives",
    audited: true,
    auditFirms: ["Trail of Bits", "OpenZeppelin"],
    riskBreakdown: { smartContract: 1.5, tokenVolatility: 2, impermanentLoss: 1, liquidityDepth: 2.5, protocolReputation: 1 },
    tags: ["Stablecoin", "L2", "No IL", "ARB Incentives"],
    url: "https://app.aave.com",
    comparables: ["aa70268e-4b52-42bf-a116-608b370f9501", "7da72d09-56ca-4ec5-a45f-59114353e487"],
  },
  {
    id: "morpho-steakusdc",
    poolId: "b55f43a8-f444-4cd8-a3a4-0a4e786ba566",
    protocol: "Morpho Blue",
    protocolLogo: "MO",
    chain: "Ethereum",
    strategyType: "Lending",
    yieldSource: "Optimized USDC lending — routes to highest Aave/Compound rate with same collateral backing",
    bestUseCase: "Yield optimization on USDC — typically 10-20% better rates vs. direct Aave/Compound",
    audited: true,
    auditFirms: ["Spearbit", "Trail of Bits"],
    riskBreakdown: { smartContract: 3, tokenVolatility: 2, impermanentLoss: 1, liquidityDepth: 4, protocolReputation: 3 },
    tags: ["Stablecoin", "Optimized", "No IL", "Morpho"],
    url: "https://app.morpho.org",
    comparables: ["aa70268e-4b52-42bf-a116-608b370f9501", "7da72d09-56ca-4ec5-a45f-59114353e487"],
  },
  {
    id: "meth-protocol",
    poolId: "b9f2f00a-ba96-4589-a171-dde979a23d87",
    protocol: "mETH Protocol",
    protocolLogo: "ME",
    chain: "Ethereum",
    strategyType: "Liquid Staking",
    yieldSource: "ETH staking rewards + MEV — mETH accrues value vs ETH over time",
    bestUseCase: "ETH liquid staking with competitive APY — mETH accepted as collateral on Mantle ecosystem",
    audited: true,
    auditFirms: ["Sigma Prime", "Halborn"],
    riskBreakdown: { smartContract: 4, tokenVolatility: 3.5, impermanentLoss: 1, liquidityDepth: 4, protocolReputation: 3 },
    tags: ["ETH", "Liquid"],
    url: "https://meth.mantle.xyz",
    comparables: ["747c1d2a-c668-4682-b9f9-296708a3dd90", "d4b3c522-6127-4b89-bedf-83641cdcd2eb"],
  },
  {
    id: "ondo-usdyc",
    poolId: "ee457473-3b5f-4b53-8c8a-fde6b2e16c8a",
    protocol: "Ondo Finance",
    protocolLogo: "ON",
    chain: "Ethereum",
    strategyType: "RWA",
    yieldSource: "US Treasury yield tokenized on-chain — USDY backed 1:1 by short-duration Treasuries",
    bestUseCase: "Regulatory-compliant yield — near risk-free rate on-chain, KYC required for US persons",
    audited: true,
    auditFirms: ["Trail of Bits", "Quantstamp"],
    riskBreakdown: { smartContract: 2, tokenVolatility: 1, impermanentLoss: 1, liquidityDepth: 3, protocolReputation: 2 },
    tags: ["RWA", "T-Bills", "KYC", "Compliant"],
    url: "https://ondo.finance",
    comparables: ["54e9b138-3146-4c1f-8dce-1cb948f5ef96", "aa70268e-4b52-42bf-a116-608b370f9501"],
  },
  {
    id: "balancer-wsteth",
    poolId: "201e5f6e-cf75-4d0e-b07f-d58da3cee23a",
    protocol: "Balancer V2",
    protocolLogo: "BA",
    chain: "Ethereum",
    strategyType: "LP",
    yieldSource: "Swap fees + BAL incentives + wstETH staking yield passthrough + veBAL bribe revenue",
    bestUseCase: "Diversified LST+AAVE LP — captures staking yield + fee revenue with moderate IL",
    audited: true,
    auditFirms: ["Trail of Bits", "Certora"],
    riskBreakdown: { smartContract: 3, tokenVolatility: 6, impermanentLoss: 6, liquidityDepth: 4, protocolReputation: 3 },
    tags: ["LP", "veBAL", "wstETH"],
    url: "https://app.balancer.fi",
    comparables: ["665dc8bc-c79d-4800-97f7-304bf368e547", "25171c4c-1877-449a-9f88-45a9f153ee31"],
  },
  {
    id: "yearn-v3-usdc",
    poolId: "7d89af7a-24c9-4292-aa38-7c71b05fbd6d",
    protocol: "Yearn V3",
    protocolLogo: "YE",
    chain: "Ethereum",
    strategyType: "Structured",
    yieldSource: "Auto-compound across Aave, Compound, Morpho — allocates dynamically to highest rate",
    bestUseCase: "Set-and-forget USDC yield optimization — gas-efficient vault batches harvests across strategies",
    audited: true,
    auditFirms: ["Trail of Bits", "Spearbit"],
    riskBreakdown: { smartContract: 4, tokenVolatility: 2, impermanentLoss: 1, liquidityDepth: 4.5, protocolReputation: 3 },
    tags: ["Auto-Compound", "Stablecoin", "Vault", "No IL"],
    url: "https://yearn.fi",
    comparables: ["b55f43a8-f444-4cd8-a3a4-0a4e786ba566", "aa70268e-4b52-42bf-a116-608b370f9501"],
  },
];

export const POOL_IDS = POOL_ENRICHMENTS.map((e) => e.poolId);
export const ENRICHMENT_BY_POOL_ID = new Map(POOL_ENRICHMENTS.map((e) => [e.poolId, e]));
export const ENRICHMENT_BY_SLUG = new Map(POOL_ENRICHMENTS.map((e) => [e.id, e]));
